### ISSUE TITLE
Responsiveness.

### ISSUE THREAD

**Issue by Zack-Dx** [Zack-Dx/Discord-Clone#1]

**Comment by JASKIRAT11011** [comment]
hi @Zack-Dx i would like to contribute on the following issue , can u assign me

**Comment by Zack-Dx** [comment]
@JASKIRAT11011 sure go ahead.

**Comment by JASKIRAT11011** [comment]
thnx ,

**Comment by Utsab5** [comment]
Hi @Zack-Dx ,
I would also like to work on this,
can you also assign me to this?

**Comment by Zack-Dx** [comment]
@Utsab5 sure but whoever throws a pull req at first it'll get merged.

**Comment by Utsab5** [comment]
okay

**Comment by Samadeen** [comment]
Is it too late to join in?.. I want to work on this also

**Comment by Zack-Dx** [comment]
> Is it too late to join in?.. I want to work on this also

@Samadeen no problem! u can work too. Welcome!
