### ISSUE TITLE
Layout Issue on mobile

### ISSUE THREAD

**Issue by Oceaneyes123** [Zack-Dx/Discord-Clone#103]
Current: 
![image](https://user-images.githubusercontent.com/42128868/194438053-434451ff-c36d-40cb-8ee3-d3b24441b742.png)

Expected: (This is from actual discord)
![image](https://user-images.githubusercontent.com/42128868/194438103-58ef8171-16f8-4dfe-aa9c-95b1a1b5cc9b.png)

Please assign. I will work on this. Thanks!

**Comment by Zack-Dx** [comment]
@Oceaneyes123 Sure mate.

**Comment by Oceaneyes123** [comment]
@Zack-Dx, I already created pull request #110 as a fixed for this issue. Thanks

**Comment by Oceaneyes123** [comment]
@Zack-Dx , branch updated with hamburger menu, and created a new pull request #115. Thanks!

**Comment by khatri7** [comment]
The layout issue should be fixed with my PR #174
