### ISSUE TITLE
Change document header

### ISSUE THREAD

**Issue by heraldjose10** [Zack-Dx/Discord-Clone#104]
#Proposed Changes:

change the header from Discord clone to Discord | Your Place to Talk and Hang Out

#Why is this feature important:

This is how it is on the original webpage

#Additional Context:

**Comment by heraldjose10** [comment]
I will fix this issue. Please assign to me. Thanks

**Comment by Zack-Dx** [comment]
@heraldjose10 Sure.

**Comment by heraldjose10** [comment]
Fixed the header @Zack-Dx. Please take a look at PR #124.
Thanks!
