### ISSUE TITLE
Change footer button style

### ISSUE THREAD

**Issue by heraldjose10** [Zack-Dx/Discord-Clone#105]
#Proposed Changes:

Change the footer button to download button and logo.

#Why is this feature important:

The padding and margin of these two elements are off in smaller viewports.

#Additional Context:

Original footer
<img width="409" alt="original_footer" src="https://user-images.githubusercontent.com/60010655/194444206-a4c50444-ac89-4d0c-ae9a-2d353ecdf271.png">

Footer on the local project
<img width="381" alt="dev_footer" src="https://user-images.githubusercontent.com/60010655/194444214-17202c7b-e3e6-4fa6-a4d8-c79e26e4c321.png">

**Comment by Burekslayer** [comment]
I can start working on this in a couple of hours (It's 4:30 AM atm). Can you assign it to me?

**Comment by Zack-Dx** [comment]
@Burekslayer @heraldjose10 done.
