### ISSUE TITLE
Adding fade animation to middle sections

### ISSUE THREAD

**Issue by A-Spiral-Forge** [Zack-Dx/Discord-Clone#121]
**Is your feature request related to a problem? Please describe.**
No, I would like to add the fade animation like there is on the original landing page in middle sections when scrolling.

**Describe the solution you'd like**
Adding animation when scrolling down to make it more similar

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by A-Spiral-Forge** [comment]
@Zack-Dx Please assign this to me

**Comment by Zack-Dx** [comment]
@A-Spiral-Forge done.
