### ISSUE TITLE
Change Discord download link / open app store depending on the operating system

### ISSUE THREAD

**Issue by huyszn** [Zack-Dx/Discord-Clone#122]
**Describe the bug**
I am on a Mac and when I clicked on the 'Download for Mac' button, I get a `DiscordSetup.exe` file download for Windows.

**To Reproduce**
1. Click on 'Download for {your operating system}' button
2. See the file that you downloaded

**Expected behavior**
When I click on the download button, download the Discord setup file for Mac when I am on a Mac machine, download the Discord setup file for Windows when I am on a Windows machine, and download the Discord setup file for Linux when I am on a Linux machine. 
Also, open the iOS App Store for the Discord app for iOS systems and open the Google Play Store for the Discord app for Android systems when you click on the download button.

**Screenshots**
<img width="1440" alt="Screen Shot 2022-10-07 at 3 19 03 AM" src="https://user-images.githubusercontent.com/46979193/194496579-ffb12ea3-1577-4f6e-b717-bead0bba04d9.png">

**Comment by Zack-Dx** [comment]
@huyszn U wanna work on this?

**Comment by huyszn** [comment]
> @huyszn U wanna work on this?

@Zack-Dx you can assign someone else to work on this

**Comment by SSHSRN** [comment]
@Zack-Dx I am working on it. Kindly assign me this issue

**Comment by Zack-Dx** [comment]
@SSHSRN done.

**Comment by SSHSRN** [comment]
#140
