### ISSUE TITLE
Background stars 

### ISSUE THREAD

**Issue by GaRev98** [Zack-Dx/Discord-Clone#139]
The background of the stars is missing

Actual:
![image](https://user-images.githubusercontent.com/90431652/194600122-af9414fa-f415-4c8e-b52b-d0f6f1eb13fd.png)

Original:
![image](https://user-images.githubusercontent.com/90431652/194600251-4a803662-a2c6-4b6a-9f83-b27713d6f7f3.png)

**Comment by Zack-Dx** [comment]
@GaRev98 wanna fix?

**Comment by GaRev98** [comment]
Someone else already solved it
