### ISSUE TITLE
Create and add Nitro page

### ISSUE THREAD

**Issue by THE-AryanKumar** [Zack-Dx/Discord-Clone#147]
#Proposed Changes: I want to create and add Nitro Page. It will be Static Webpage.

#Why is this feature important: Their is lots of empty space. Nitro page will fill it.

#Additional Context:

**Comment by Zack-Dx** [comment]
@THE-AryanKumar u want to?

**Comment by THE-AryanKumar** [comment]
Yess..., pls /assign me

**Comment by Zack-Dx** [comment]
@THE-AryanKumar done mate.

**Comment by THE-AryanKumar** [comment]
Can you label it too "Hacktoberfest2022"

**Comment by THE-AryanKumar** [comment]
#158 Review and approve....

**Comment by Zack-Dx** [comment]
@THE-AryanKumar throw a new pr fixing that issue too.
