### ISSUE TITLE
This Section fonts are not suitable for dark Mode

### ISSUE THREAD

**Issue by BhaveshAnandpara** [Zack-Dx/Discord-Clone#150]
**Describe the bug**
the "RELIABLE TECH FOR STAYING CLOSE" section font colors are not suitable for dark theme which makes UI bad

**Screenshots**
![Screenshot (315)](https://user-images.githubusercontent.com/87887912/194618244-fb122f81-0abf-4dc6-bd87-d98f8f2dcc35.png)

**Comment by Zack-Dx** [comment]
@BhaveshAnandpara u wanna fix?

**Comment by BhaveshAnandpara** [comment]
@Zack-Dx yeah sure ! you can assign me this task and please add hacktoberfest tag 🙌🙌

**Comment by Zack-Dx** [comment]
> @Zack-Dx yeah sure ! you can assign me this task and please add hacktoberfest tag 🙌🙌

done.
