### ISSUE TITLE
Add hover effect to login button

### ISSUE THREAD

**Issue by SujalSamai** [Zack-Dx/Discord-Clone#160]
**Describe the bug**
- The login button right now, doesn't looks like an actual button as it is not responsive at all. We can add hover effect to it and later add a login page to it.

**To Reproduce**
1. Go to 'Home page'
2. Try to hover on Login button

**Expected behavior**
There should be a hover effect in login button to make it look like an actual button which is responsive.

**Screenshots**
![image](https://user-images.githubusercontent.com/87236576/194689171-1666a997-17d6-44a5-8101-1d98c2ad2839.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Zack-Dx** [comment]
@SujalSamai u wanna fix?

**Comment by hackbysarthak03** [comment]
Hey @Zack-Dx , Can u assign me this to do this ?

**Comment by SujalSamai** [comment]
> @SujalSamai u wanna fix?

Yes I would like to fix this

**Comment by coder-chahal** [comment]
Hlo @Zack-Dx, can i work it too if yes then please assign issue to me:)
