### ISSUE TITLE
The button to close hamburger menu in night mode is not visible.

### ISSUE THREAD

**Issue by SujalSamai** [Zack-Dx/Discord-Clone#161]
**Describe the bug**
The button to close the hamburger menu in the night mode is not visible. So user can't understand how to close the menu.

**To Reproduce**
1. Go to any page.
2. Click on night mode.
3. Click on Hamburger menu in mobile layout

**Expected behavior**
There should be cross button to close the hamburger menu when using in night mode. Although, night mode can't be accessed through mobile, but still if anyone uses desktop mode, they can get that feature and will encounter the bug.

**Screenshots**
![image](https://user-images.githubusercontent.com/87236576/194689735-f7a8c4ac-75dc-4ae1-8df4-d0973bd955dd.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] -Windows 11
 - Browser [e.g. chrome, safari] - Chrome

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] - Realme GT Master Editiom
 - OS: [e.g. iOS8.1] - Android 12
 - Browser [e.g. stock browser, safari] -Chrome

**Additional context**

**Comment by Zack-Dx** [comment]
@SujalSamai u wanna fix?
