### ISSUE TITLE
Not optimized for smartphones

### ISSUE THREAD

**Issue by TaufeeqRiyaz** [Zack-Dx/Discord-Clone#27]
**Describe the bug**
Not optimized to use on smartphones

**To Reproduce**
open the website on a smartphone/inspect

https://taufeeqriyaz.github.io/Discord-Clone/

**Comment by cgrkzlkn** [comment]
Hi, I can make the website mobile responsive.

@Zack-Dx please assign it to me with hacktoberfest label.

Thanks.

**Comment by Zack-Dx** [comment]
> Hi, I can make the website mobile responsive.
> 
> @Zack-Dx please assign it to me with hacktoberfest label.
> 
> Thanks.

For sure❤️
