### ISSUE TITLE
No download Icon before the Download for Windows button

### ISSUE THREAD

**Issue by Mukul-svg** [Zack-Dx/Discord-Clone#29]
in original discord page there is a download icon before the "Download for Windows" button

**Comment by Zack-Dx** [comment]
@Mukul-svg u wanna add it?

**Comment by Shivangbhatnagar237** [comment]
I can add it @Zack-Dx

**Comment by Zack-Dx** [comment]
> I can add it @Zack-Dx

it's there but u can fix the alignment of it else change that icon.

**Comment by Shivangbhatnagar237** [comment]
Hey @Zack-Dx , I'm modifying the website's code, but the changes aren't getting reflected on the live server that I'm using on VS Code. I don't know how this is happening, but this is obstructing my way to solving this issue.
![hack2](https://user-images.githubusercontent.com/47966497/194108086-20427902-e49e-47cd-a4a7-29b2175016dc.PNG)
![hack1](https://user-images.githubusercontent.com/47966497/194108095-32757227-00b0-4f6f-9004-f36583ae979b.PNG)

In the first image labeled hack1.png, you can see that "Download for Windows" is the text on the output

**Comment by Shivangbhatnagar237** [comment]
and in my code, you can see "Download for Mac" is there.

**Comment by Shivangbhatnagar237** [comment]
No issues, I created a PR regarding this.
