### ISSUE TITLE
Hamburger menu for mobiles devices.

### ISSUE THREAD

**Issue by Zack-Dx** [Zack-Dx/Discord-Clone#43]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by VidishaAG** [comment]
Can I be assigned please?

**Comment by Zack-Dx** [comment]
> Can I be assigned please?

@VidishaAG Sure. Welcome! check discord.com for reference.

**Comment by achiverram28** [comment]
Can I also work on it

**Comment by Zack-Dx** [comment]
@achiverram28 sure.

**Comment by qudus2019** [comment]
Kindly assign this to me

**Comment by Zack-Dx** [comment]
> Kindly assign this to me

@qudus2019 done.

**Comment by HarshJa1n** [comment]
Kindly assign this to me too

**Comment by Zack-Dx** [comment]
> Kindly assign this to me too

@HarshJa1n Done.
