### ISSUE TITLE
Fix The position of buttons

### ISSUE THREAD

**Issue by Priyanshup891** [Zack-Dx/Discord-Clone#45]
#Proposed Changes:

#Why is this feature important:

#Additional Context:

**Comment by Zack-Dx** [comment]
@Priyanshup891 which?

**Comment by Priyanshup891** [comment]
In the hero section

**Comment by Zack-Dx** [comment]
> In the hero section

ss.

**Comment by Priyanshup891** [comment]
![Screenshot from 2022-10-06 10-31-55](https://user-images.githubusercontent.com/80090818/194218429-4f00c886-b5d7-4ae5-a5e0-0baf2b7dfd14.png)

**Comment by Zack-Dx** [comment]
@Priyanshup891 u wanna fix?

**Comment by Priyanshup891** [comment]
yes

**Comment by Zack-Dx** [comment]
> yes

done.
