### ISSUE TITLE
typography fix

### ISSUE THREAD

**Issue by tech0x10** [Zack-Dx/Discord-Clone#52]
1. font weight is bold compare to the official website 
2. should add line height to make text more readable

**Comment by Zack-Dx** [comment]
@tech0x10 u wanna fix?

**Comment by tech0x10** [comment]
why not!

**Comment by Zack-Dx** [comment]
> why not!

@tech0x10 done.

**Comment by priyanshu6781** [comment]
Hey, I would like to contribute towards this. Could you please assign me this task?

**Comment by priyanshu6781** [comment]
Hey, it's done

**Comment by Zack-Dx** [comment]
> Hey, I would like to contribute towards this. Could you please assign me this task?

@priyanshu6781 assigned.

**Comment by tech0x10** [comment]
iam also adding some javascript so the scroll button will only appear when the users will scroll down the page.
