### ISSUE TITLE
Light/Dark mode toggle

### ISSUE THREAD

**Issue by lordashuchauhan** [Zack-Dx/Discord-Clone#60]
Light and Dark mode toggle button.
@Zack-Dx assign me this under Hacktoberfest 2022

**Comment by lordashuchauhan** [comment]
@Zack-Dx  kindly review my PR #58, under hacktoberfest 2022



![Screenshot (1)](https://user-images.githubusercontent.com/100701424/194278381-32180700-6cb5-4c38-b5de-22a7630ce3db.png)
![Screenshot (2)](https://user-images.githubusercontent.com/100701424/194278396-0047e06c-d0b7-455d-9584-ac3536e65eb9.png)
![Screenshot (3)](https://user-images.githubusercontent.com/100701424/194278399-5bed1564-35d3-4da8-ba77-be7e270ead14.png)
![Screenshot (4)](https://user-images.githubusercontent.com/100701424/194278404-daaab9bb-3399-4f2d-a06a-748785ac4030.png)
![Screenshot (5)](https://user-images.githubusercontent.com/100701424/194278407-206a7c43-f5f9-48b6-a16e-ed60e535d419.png)
![Screenshot (7)](https://user-images.githubusercontent.com/100701424/194278414-6d3ecd08-8ecb-4734-9811-d2c9473e78a0.png)
![Screenshot (8)](https://user-images.githubusercontent.com/100701424/194278426-0a521ec6-fe47-420a-b068-e1925dc4ad93.png)
![Screenshot (9)](https://user-images.githubusercontent.com/100701424/194278430-15ef361e-4854-4aaa-9c9e-5d121d7978e0.png)

**Comment by Zack-Dx** [comment]
@lordashuchauhan try to make the fonts white after dark mode is toggled and make sure to maintain responsiveness. Thanks!
