### ISSUE TITLE
Handburger menu and responsive Footer

### ISSUE THREAD

**Issue by Rahul-Palamarthi** [Zack-Dx/Discord-Clone#75]
I want to make Header as Handburger menu and also want to make footer responsive

**Comment by Zack-Dx** [comment]
@Rahul-Palamarthi Sure go ahead.

**Comment by ayushpatil9696** [comment]
I would like to contribute in this. could you share more info on this

**Comment by Rahul-Palamarthi** [comment]
They actually developed by some one else and I was late. So someone has build it before my Pull Request

**Comment by ayushpatil9696** [comment]
Ok bruh (0_0)

**Comment by ayushpatil9696** [comment]
It's fine thanks for letting me know.
