### ISSUE TITLE
Improve UI in "Where hanging out is easy" section

### ISSUE THREAD

**Issue by TIGGERKUB** [Zack-Dx/Discord-Clone#82]
**Describe the bug**

In the "Where hanging out is easy" section, there is a png image that has a low resolution as you can see in the screenshot. So, I suggest using an SVG image instead. In addition, the background color of this section should be light gray (#f6f6f6) according to the real discord landing page.

**Screenshots**
<img width="1356" alt="Screen Shot 2565-10-06 at 22 26 58" src="https://user-images.githubusercontent.com/38415653/194355252-56cb5506-53dc-4bb4-a82d-bd687774776b.png">

**Additional context**
I can do this if you would like

**Comment by TaufeeqRiyaz** [comment]
@Zack-Dx I've fixed this in PR #81

**Comment by TIGGERKUB** [comment]
> @Zack-Dx I've fixed this in PR #81
> 
> https://discord-clone-eshy8mm0v-zack-dx.vercel.app/

Oh! I'm sorry, I didn't know that because the link provided on the repo page is still using a png image. By the way, the link you provided still uses white background which should be a light gray according to the real one. I can do that if you'd like.

**Comment by TaufeeqRiyaz** [comment]
> > @Zack-Dx I've fixed this in PR #81
> > https://discord-clone-eshy8mm0v-zack-dx.vercel.app/
> 
> Oh! I'm sorry, I didn't know that because the link provided on the repo page is still using a png image. By the way, the link you provided still uses white background which should be a light gray according to the real one. I can do that if you'd like.

Why are you sorry? I fixed it after you pointed it out :)

**Comment by Zack-Dx** [comment]
> @TaufeeqRiyaz Actually I'm waiting for the maintainer to assign the issue to me. You should wait for the maintainer to assign before opening the PR too because we will know who is working on this issue so there will be no conflict.

You want to contribute?

**Comment by TIGGERKUB** [comment]
Yep!
