### ISSUE TITLE
css changes

### ISSUE THREAD

**Issue by kaavyabaranwal** [Zack-Dx/Discord-Clone#94]
text to be made more similar to main website, in terms of font weight, font , and words after which there is a line change

**Comment by acenasir** [comment]
@Zack-Dx Can I take this? Provide more info of changes needed

**Comment by kaavyabaranwal** [comment]
> @acenasir we are supposed to create our own issues...and then resolve them 😀

**Comment by acenasir** [comment]
Thanks @kaavyabaranwal Will do!
