### ISSUE TITLE
RELIABLE TECH FOR STAYING CLOSE section is missing correct color bg

### ISSUE THREAD

**Issue by acenasir** [Zack-Dx/Discord-Clone#99]
RELIABLE TECH FOR STAYING CLOSE section is missing correct color bg

**Comment by Oceaneyes123** [comment]
Hello, want to work on this. Please assign. Thanks

**Comment by heraldjose10** [comment]
I can fix this issue. Please assign this to me.

**Comment by heraldjose10** [comment]
Fixed this issue. Please checkout PR #131 
Thanks

**Comment by heraldjose10** [comment]
Can we close this issue? @acenasir @Zack-Dx
